name: Bug Report
description: Report a bug in Ainur Protocol
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for reporting a bug!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - L1 Blockchain (Temporal)
        - L3 P2P Network
        - L4 AACL Protocol
        - L5 Execution Runtime
        - L6 Economic Layer
        - L5.5 Verification (Warden)
        - L4.5 MARL (Nexus)
        - SDK
        - Documentation
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please include relevant logs or error messages
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: [e.g. Ubuntu 22.04]
        - Rust Version: [e.g. 1.75.0]
        - Node Version: [e.g. v1.0.0]
      placeholder: |
        - OS: 
        - Rust Version: 
        - Node Version: 
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical - System unusable
        - High - Major functionality broken
        - Medium - Minor functionality impacted
        - Low - Cosmetic issue
    validations:
      required: true
