name: Security Vulnerability
description: Report a security vulnerability (for non-critical issues only, critical issues should be reported privately)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT**: If this is a critical vulnerability that could affect mainnet or user funds, 
        please DO NOT create a public issue. Instead, report it privately to security@ainur.ai
        
        Only use this form for low-severity security issues that can be disclosed publicly.

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I confirm this is NOT a critical vulnerability
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - L1 Blockchain (Temporal)
        - L3 P2P Network
        - L4 AACL Protocol
        - L5 Execution Runtime
        - L6 Economic Layer
        - L5.5 Verification (Warden)
        - Smart Contracts
        - Cryptography
    validations:
      required: true

  - type: textarea
    id: vulnerability
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: Describe the vulnerability...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Analysis
      description: What is the potential impact of this vulnerability?
      placeholder: Describe potential impact...
    validations:
      required: true

  - type: textarea
    id: exploit
    attributes:
      label: Proof of Concept
      description: If possible, provide a proof of concept
      render: shell

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Fix
      description: If you have suggestions for fixing the vulnerability
      placeholder: Describe potential fixes...

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      options:
        - Low - Minimal impact
        - Medium - Limited impact
        - High - Significant impact (should be reported privately)
    validations:
      required: true
